// <auto-generated />
using BEZendframework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BEZendframework.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210729162418_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BEZendframework.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("idsector")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("idzona")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sueldo")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("DBPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
